services:
  ydb:
    image: ydbplatform/local-ydb:latest
    hostname: localhost
    container_name: ydb-local
    network_mode: host

  ydb-mcp:
    build:
      context: .
      dockerfile: Dockerfile.ydb-mcp
      network: host
    depends_on:
      - ydb
    network_mode: host
    env_file:
      # Load ydb.env if it exists, fallback to localhost defaults from Dockerfile
      - path: ./ydb.env
        required: false
    volumes:
      # Mount authorized_key.json if it exists (optional for localhost)
      - ./authorized_key.json:/app/authorized_key.json:ro
    # MCP works through stdin/stdout, not network ports
    # Container will be created and removed automatically with --rm flag
    stdin_open: true
    tty: false

  notes-app:
    build:
      context: .
      network: host
    container_name: notes-app
    network_mode: host
    depends_on:
      - ydb
    env_file:
      # Load ydb.env if it exists, fallback to localhost defaults from Python app
      - path: ./ydb.env
        required: false
    volumes:
      - .:/app
    profiles:
      - app
