version: '3.8'

services:
  ydb:
    image: ydbplatform/local-ydb:latest
    hostname: localhost
    container_name: ydb-local
    ports:
      - "2136:2136"   # gRPC endpoint
      - "8765:8765"   # Web UI

  notes-app:
    build: .
    container_name: notes-app
    network_mode: host
    depends_on:
      - ydb
    environment:
      - YDB_ENDPOINT=grpc://localhost:2136
      - YDB_DATABASE=/local
    profiles:
      - app
